name: mongoDB.app
url: https://gcollazo.github.io/mongodbapp
description: The easiest way to get started with mongoDB on the Mac
repoUrl: https://github.com/gcollazo/mongodbapp

exclude:
  - Gemfile
  - Gemfile.lock
